apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-ingestion-config
  namespace: agrosolutions
  labels:
    app: sensor-ingestion
    component: backend
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  RabbitMQ__Host: "rabbitmq.agrosolutions.svc.cluster.local"
  RabbitMQ__Port: "5672"
  RabbitMQ__QueueName: "sensor-data-queue"
