apiVersion: v1
kind: Service
metadata:
  name: sensor-ingestion
  namespace: agrosolutions
  labels:
    app: sensor-ingestion
    component: backend
spec:
  type: ClusterIP
  selector:
    app: sensor-ingestion
  ports:
  - port: 8080
    targetPort: 8080
    name: http
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-ingestion-external
  namespace: agrosolutions
  labels:
    app: sensor-ingestion
    component: backend
spec:
  type: NodePort
  selector:
    app: sensor-ingestion
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
    name: http
    protocol: TCP
